#!/usr/bin/env python


from __future__ import division, print_function


import shelper.bookmarks

import subprocess
import sys


def main():
    bookmark_name = sys.argv[1]
    if bookmark_name[0] == "_":
        raise KeyError(bookmark_name)

    bookmark_func = getattr(shelper.bookmarks, bookmark_name)
    arg = " ".join(sys.argv[2:])

    url = bookmark_func(arg)

    subprocess.check_call(("open", url.to_url()))


if __name__ == "__main__":
    main()
