#!/bin/bash


TIMESTAMP_FORMAT='%Y%m%d%H%M%S'
HASH_CHARS=8

TOPLEVEL="$(git rev-parse --show-toplevel)"
if [[ -z "$TOPLEVEL" ]]; then
	git --version && \
		echo Are you in a git repository? || \
		echo Is Git installed?
	exit 1
fi

cd "$TOPLEVEL"

BASENAME="$(basename -- "$TOPLEVEL")"
TIMESTAMP="$(date +"$TIMESTAMP_FORMAT")"
HASH="$(git rev-parse --short=$HASH_CHARS HEAD)"
if [[ -z "$HASH" ]]; then
	exit 1
fi

ZIPNAME="$BASENAME-$TIMESTAMP-$HASH.zip"
git ls-files | zip -9 -@ "$ZIPNAME"
