#!/bin/bash
. "$(dirname -- "$0")"/support.bash


if [[ $# -eq 0 ]]; then
	__yc_die_usage 'PATH [PATH...]'
fi

TEMP_DIR=$(mktemp -d yc_jpegopt.XXXXXX)
if [[ -z $TEMP_DIR ]];
	__yc_die 'Failed to make temp dir'
fi

TEMP_FILE="$TEMP_DIR/temp.jpg"

cleanup()
{
	rm -f -- "$TEMP_FILE"
	rmdir -- "$TEMP_DIR"
	exit 255
}

trap cleanup EXIT

RESULT=0
for image in "$@"; do
	jpegtran -copy none -optimize -- "$image" > "$TEMP_FILE" && \
		cat "$TEMP_FILE" > "$image" || {
			RESULT=$(( $? > $RESULT ? $? : $RESULT ))
			__yc_err $0: $image: failed
		}
done

exit $RESULT
