#!/usr/bin/env python


from __future__ import division, print_function


import shelper.bookmarks

import os.path
import subprocess
import sys


def exec_to_func_name(path):
	stem, _ = os.path.splitext(os.path.basename(path))
	return stem.replace("-", "_")


def main():
	func_name = exec_to_func_name(sys.argv[0])

	# always deny use of a name with a leading underscore
	if func_name == "" or func_name[0] == "_":
		raise KeyError(func_name)

	bookmark_func = getattr(shelper.bookmarks, func_name)
	url = bookmark_func(sys.argv[1:])
	subprocess.check_call(("open", str(url)))


if __name__ == "__main__":
	main()
