#!/usr/bin/python

from argparse import ArgumentParser
import os.path
import subprocess
import sys

SCRIPT="""\
on run argv
    local errorCount
    set errorCount to 0
    repeat with thePath in argv
        try
            tell application "Finder" to move (thePath as POSIX file) to trash
            log thePath
        on error errorText from errorSource
            set errorCount to errorCount + 1
            log thePath & ": " & errorText
        end try
    end repeat

    if errorCount > 0 then
        error "Failed to move " & errorCount & " file(s) to the Trash."
    end if
end run
"""

p = ArgumentParser(
        description="""
            Deletes files or folders by moving them to the Trash.
        """
)

p.add_argument('files', nargs='+')

args = p.parse_args()

cmd = ['osascript']
for line in SCRIPT.strip().splitlines():
    cmd.extend(('-e', line))
cmd.extend(os.path.abspath(p) for p in args.files)

exit_code = subprocess.call(cmd)
sys.exit(exit_code)
